2015-10-02 00:43:00 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:01:28 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:02:13 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:10 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:13 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:15 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:16 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:18 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:19 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:38 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:08:25 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:37 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:41 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:44 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:45 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:47 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:28:33 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:28:36 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:23 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:26 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:27 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:29 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:30 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:30:05 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:31:43 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:32:14 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:32:30 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:36 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:36 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:37 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:39 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:43 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:34:03 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:18:06 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:18:14 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:18:32 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:20:07 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:20:42 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:23:15 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '6' for key 'PRIMARY'")
2015-10-02 10:23:35 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:26:54 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:27:15 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:29:07 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:29:27 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:30:22 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:32:43 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:32:47 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:09 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:16 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:33:21 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:23 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:23 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:24 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:24 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:26 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:26 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:43 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:33:47 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:49 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:50 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:50 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:50 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:52 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:33:52 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:34:04 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:34:09 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:36:11 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:36:15 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:36:16 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:36:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:36:24 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:36:28 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:36:55 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:06 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:11 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:37:15 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:16 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:16 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:18 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:19 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:37:19 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:42:10 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:42:14 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:42:18 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:42:19 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:42:19 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:42:20 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:42:20 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:42:21 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:42:25 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:22 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:43:25 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:26 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:26 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:26 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:27 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:52 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:43:56 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:57 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:58 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:58 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:43:58 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:11 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:12 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:13 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:13 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:13 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:13 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:46:17 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:50:18 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:52:01 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:52:04 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:52:09 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:52:10 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:56:09 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:56:13 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:57:30 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:57:37 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:59:22 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:59:26 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 10:59:48 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 10:59:51 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:00:15 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:00:18 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:00:39 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:00:43 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:13:25 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:19:16 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:19:22 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:20:55 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:21:31 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:22:03 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:23:28 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:24:05 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:24:12 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:24:23 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:24:26 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:24:36 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:25:10 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:25:13 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:26:24 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:26:27 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:26:45 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:27:46 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:27:52 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:28:04 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:28:10 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:28:43 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:28:46 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:28:51 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:28:58 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:29:01 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:29:54 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:29:58 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:30:41 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:30:44 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:31:04 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:31:08 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:31:18 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:31:20 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:31:26 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:32:26 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:32:30 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:32:42 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:32:44 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:32:46 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:33:22 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:33:26 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:34:19 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:34:27 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:35:04 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:35:09 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:35:53 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:35:56 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:36:01 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:36:45 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:36:49 main.py[line:78] ERROR 数据写入失败:(1062, "Duplicate entry '1' for key 'PRIMARY'")
2015-10-02 11:36:52 main.py[line:78] ERROR 数据写入失败:(1054, "Unknown column 'e4wrfwe' in 'where clause'")
2015-10-02 11:36:56 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 11:36:58 main.py[line:78] ERROR 数据写入失败:(1054, "Unknown column 'e4wrfwe' in 'where clause'")
2015-10-02 11:37:02 main.py[line:78] ERROR 数据写入失败:(1054, "Unknown column 'e4wrfwe' in 'where clause'")
2015-10-02 11:37:09 main.py[line:78] ERROR 数据写入失败:(1054, "Unknown column 'e4wrfwe' in 'where clause'")
2015-10-02 11:37:12 main.py[line:78] ERROR 数据写入失败:(1054, "Unknown column 'e4wrfwe' in 'where clause'")
2015-10-02 11:37:17 main.py[line:78] ERROR 数据写入失败:(1054, "Unknown column 'e4wrfwe' in 'where clause'")
