2015-10-02 00:43:00 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:01:28 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:02:13 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:10 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:13 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:15 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:16 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:18 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:19 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:03:38 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:08:25 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:37 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:41 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:44 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:45 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:12:47 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:28:33 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:28:36 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:23 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:26 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:27 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:29 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:29:30 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:30:05 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:31:43 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:32:14 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:32:30 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:36 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:36 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:37 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:39 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:33:43 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
2015-10-02 09:34:03 main.py[line:102] ERROR 数据执行失败:(1054, "Unknown column 'id' in 'field list'")
